### ISSUE TITLE
Error During Export

### ISSUE THREAD

**Issue by FlynnD273** [Falano/kritaSpritesheetManager#10]
When I run the script, imported from the downloaded zip file, I get an error. I've tried different settings, as well as using the default settings. I am using Krita 4.3.0

Here is the message:

IndexError
Python 3.8.1: C:\Program Files\Krita (x64)\bin\krita.exe
Sat Aug  1 15:35:51 2020

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Users\User\AppData\Roaming\krita\pykrita\spritesheetExporter\uispritesheetexporter.py in confirmButton(self=<spritesheetExporter.uispritesheetexporter.UISpritesheetExporter object>)
  398         else:
  399             # important: we reset spritesheetexporter's spritesExportDir
  400             self.exp.spritesExportDir = self.exp.defaultPath
  401         self.exp.export()
  402         self.mainDialog.hide()
self = <spritesheetExporter.uispritesheetexporter.UISpritesheetExporter object>
self.exp = <spritesheetExporter.spritesheetexporter.SpritesheetExporter object>
self.exp.export = <bound method SpritesheetExporter.export of <spr....spritesheetexporter.SpritesheetExporter object>>

 C:\Users\User\AppData\Roaming\krita\pykrita\spritesheetExporter\spritesheetexporter.py in export(self=<spritesheetExporter.spritesheetexporter.SpritesheetExporter object>, debugging=False)
  322         while (frameIDNum < self.end):
  323             doc.waitForDone()
  324             if(self.layersStates[frameIDNum]):
  325                 img = str(spritesExportPath(fileNum(frameIDNum) + ".png"))
  326                 if(debugging):
self = <spritesheetExporter.spritesheetexporter.SpritesheetExporter object>
self.layersStates = []
frameIDNum = 0
IndexError: list index out of range
    __cause__ = None
    __class__ = <class 'IndexError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of IndexError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of IndexError object>
    __doc__ = 'Sequence index out of range.'
    __eq__ = <method-wrapper '__eq__' of IndexError object>
    __format__ = <built-in method __format__ of IndexError object>
    __ge__ = <method-wrapper '__ge__' of IndexError object>
    __getattribute__ = <method-wrapper '__getattribute__' of IndexError object>
    __gt__ = <method-wrapper '__gt__' of IndexError object>
    __hash__ = <method-wrapper '__hash__' of IndexError object>
    __init__ = <method-wrapper '__init__' of IndexError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of IndexError object>
    __lt__ = <method-wrapper '__lt__' of IndexError object>
    __ne__ = <method-wrapper '__ne__' of IndexError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of IndexError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of IndexError object>
    __repr__ = <method-wrapper '__repr__' of IndexError object>
    __setattr__ = <method-wrapper '__setattr__' of IndexError object>
    __setstate__ = <built-in method __setstate__ of IndexError object>
    __sizeof__ = <built-in method __sizeof__ of IndexError object>
    __str__ = <method-wrapper '__str__' of IndexError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ('list index out of range',)
    with_traceback = <built-in method with_traceback of IndexError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\krita\pykrita\spritesheetExporter\uispritesheetexporter.py", line 401, in confirmButton
    self.exp.export()
  File "C:\Users\User\AppData\Roaming\krita\pykrita\spritesheetExporter\spritesheetexporter.py", line 324, in export
    if(self.layersStates[frameIDNum]):
IndexError: list index out of range

**Comment by Falano** [comment]
My bad. It should be fixed now.
Thanks for telling me!

**Comment by FlynnD273** [comment]
Works perfectly now! I know that I should probably enter this in a separate issue, but it seems kind of low-priority. Would you be able to somehow not include the onionskinning in the export? It works absolutely fine if I turn it off, but it shows up when I leave onionskinning on.

**Comment by Falano** [comment]
Short answer: I'll see what I can do, but probably not.

Long answer: The way the plugin works is that it exports each frame as images, then re-imports those images in a new krita file, each at the right position. So you see the onion skinning because by default, krita exports it.
An easy solution would be to disable it at script start and re-enable it when finished, but after a quick look I haven't found a way to do it in scripting, so probably the onion skin isn't in the krita python api.
Another easy solution would be to use, instead of the equivalent to File>Export (which exports the onion skin), the equivalent to File>Render Animation (which doesn't), but I haven't found that one either in the api.
A better solution would be to create a pull request to krita itself so it doesn't ever export onion skins, but it's also harder for me.

I'll keep you updated if I manage to get one of those solutions working.

**Comment by FlynnD273** [comment]
Alright. Thank you for responding so quickly! This is a really helpful plugin, and I'm really glad you were able to get it to work for me. Thanks!
