### ISSUE TITLE
Folder export problem

### ISSUE THREAD

**Issue by PabloDevGit** [Falano/kritaSpritesheetManager#11]
Hi, great job, there is only one problem.
When I configure an export folder, then it is not remembered and I have to configure it again.
That is, in each export I must configure the folder.

**Comment by Falano** [comment]
It should be fixed; as long as you don't close krita, it will remember, for additional exports, the export path you chose

**Comment by PabloDevGit** [comment]
Ok, I will try it next time to see if it works correctly as you say, thanks.
