### ISSUE TITLE
it deletes the files

### ISSUE THREAD

**Issue by fridaynightfunkinguy** [Falano/kritaSpritesheetManager#15]
when I make the sprite sheet it deletes the folder files, is it my antivirus or a bug
also, it crashes every time I make a sprite sheet

**Comment by Falano** [comment]
Hi! Thanks for the bug report.
- About the crashing:
It works fine on my end, so I'd need more information to try to fix it.
What's your OS? What version of krita are you using? What are your export settings? Maybe try to start krita from the terminal and check the error messages when it crashes.
- About the "it deletes the folder files":
I'm not sure what files you're talking about? If it's the individual sprites that the exporter creates then puts together to make the spritesheet, then that's on purpose: you can disable this behaviour by clicking "Use Custom Export Settings" and then unchecking "Remove individual sprites?".
