### ISSUE TITLE
White background instead of transparent

### ISSUE THREAD

**Issue by Chae4ek** [Falano/kritaSpritesheetManager#19]
Exporting transparent images actually fills the background with white in spritesheet, but it's transparent in individual sprites.

Environment: Windows 10, Krita 5.1.5

**Comment by nagidev** [comment]
Facing the same issue.
Windows 10, Krita 5.1.5
Pop_OS 22.04 Krita 5.1.5

**Comment by Astra307** [comment]
Same! 
Windows 11, Krita 5.1.5
It used to work well with the Krita 4.x.x series, but stopped working with one of the new updates.

**Comment by eh-jogos** [comment]
Same, Krita 5.1.5 as well
Using Manjaro with i3

**Comment by Chae4ek** [comment]
fixed in #20
