### ISSUE TITLE
start and end parameters don't let me insert more then 2 digits

### ISSUE THREAD

**Issue by Haklak** [Falano/kritaSpritesheetManager#23]
Start and end don't let me insert a value higher than 99. The increment arrow is grayed out. This prevents me from having a specific start or end point higher than 99 other than -1.
![image_2023-11-21_223013342](https://github.com/Falano/kritaSpritesheetManager/assets/151676499/3f992350-63ed-43d0-b65e-43d4b32724f5)

**Comment by Falano** [comment]
should be fixed now, new maximum is 9999. I didn't change Rows, Columns or Step as having more than 99 seemed unnecessary for them.
Thanks for letting me know!
