### ISSUE TITLE
Ubuntu Krita - doesn't show up in python plugin manager

### ISSUE THREAD

**Issue by HeroicNate** [Falano/kritaSpritesheetManager#3]
Followed the directions. Was not able to see the option in the python plugin manager. Even after restarting krita.

**Comment by Falano** [comment]
Are you sure you have the right version of Krita (4.2.x)?

**Comment by HeroicNate** [comment]
So I was messing around more and got it working, but not how the readme
says to. First I learned that that you want to unzip the file and only
take the sub folder SpriteSheetExporter(maybe "no duh" but I didn't know),
and put it in the pykrita folder in the resources folder for it to show up
in the python plugins. Just putting it in the resources folder didn't let
anything show up. But even when I did get it to show up from the pykrita folder it was greyed out
and not working.

So I deleted all those copied files when I noticed the Krita python plugin
importer script. When I used that on the zip I was able to restart krita,
activate, and use it. Now it worked and spit out a sprite sheet. Pretty
nifty!

So my process for getting it to work:

   - *Download* using the green "clone or download" button on this page,
   then clicking "download as zip"
   - *Open Krita, go to Tools > Scripts > Import Python Plugin *then select
   the zip file you downloaded. Krita will then ask you to activate the
   script. Click ok.
   - *Restart Krita*
   - *Activate the script in Krita* by going to Settings > Configure Krita
   > Python Plugin Manager and checking Spritesheet Exporter
   - *Restart Krita*
   - you can now use it in Tools > Scripts > Export As Spritesheet

**Comment by Falano** [comment]
Whoops, indeed, seems like you only need the subfolder and the .desktop file (probably why yours was greyed out) in the resources folder.
I updated the readme with both methods.
Thanks a lot for seeing this error in the readme and taking the time to find a solution!
I'm glad you find the plugin useful
