### ISSUE TITLE
Error using custom export setting

### ISSUE THREAD

**Issue by gle2n** [Falano/kritaSpritesheetManager#7]
Hi,
when using a custom export setting and not letting 0 for the Rows and Columns, I get the following error message :
(windows 10 1903, krita 4.2.8)

NameError
Python 3.6.2: python
Tue Dec 17 16:06:18 2019

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Users\the-g\AppData\Roaming\krita\pykrita\spritesheetExporter\uispritesheetexporter.py in confirmButton(self=<spritesheetExporter.uispritesheetexporter.UISpritesheetExporter object>)
  378         else:
  379             # important: we reset spritesheetexporter's spritesExportDir
  380             self.exp.spritesExportDir = self.exp.defaultPath
  381         self.exp.export()
  382         self.mainDialog.hide()
self = <spritesheetExporter.uispritesheetexporter.UISpritesheetExporter object>
self.exp = <spritesheetExporter.spritesheetexporter.SpritesheetExporter object>
self.exp.export = <bound method SpritesheetExporter.export of <spr....spritesheetexporter.SpritesheetExporter object>>

 C:\Users\the-g\AppData\Roaming\krita\pykrita\spritesheetExporter\spritesheetexporter.py in export(self=<spritesheetExporter.spritesheetexporter.SpritesheetExporter object>, debugging=False)
  202 
  203         # if only one is specified, guess the other
  204         elif (self.rows == defaultSpace):
  205             self.rows = ceil(float(framesNum)/self.columns)
  206 
self = <spritesheetExporter.spritesheetexporter.SpritesheetExporter object>
self.rows = 1
defaultSpace undefined
NameError: name 'defaultSpace' is not defined
    __cause__ = None
    __class__ = <class 'NameError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of NameError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of NameError object>
    __doc__ = 'Name not found globally.'
    __eq__ = <method-wrapper '__eq__' of NameError object>
    __format__ = <built-in method __format__ of NameError object>
    __ge__ = <method-wrapper '__ge__' of NameError object>
    __getattribute__ = <method-wrapper '__getattribute__' of NameError object>
    __gt__ = <method-wrapper '__gt__' of NameError object>
    __hash__ = <method-wrapper '__hash__' of NameError object>
    __init__ = <method-wrapper '__init__' of NameError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of NameError object>
    __lt__ = <method-wrapper '__lt__' of NameError object>
    __ne__ = <method-wrapper '__ne__' of NameError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of NameError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of NameError object>
    __repr__ = <method-wrapper '__repr__' of NameError object>
    __setattr__ = <method-wrapper '__setattr__' of NameError object>
    __setstate__ = <built-in method __setstate__ of NameError object>
    __sizeof__ = <built-in method __sizeof__ of NameError object>
    __str__ = <method-wrapper '__str__' of NameError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("name 'defaultSpace' is not defined",)
    with_traceback = <built-in method with_traceback of NameError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Users\the-g\AppData\Roaming\krita\pykrita\spritesheetExporter\uispritesheetexporter.py", line 381, in confirmButton
    self.exp.export()
  File "C:\Users\the-g\AppData\Roaming\krita\pykrita\spritesheetExporter\spritesheetexporter.py", line 204, in export
    elif (self.rows == defaultSpace):
NameError: name 'defaultSpace' is not defined

**Comment by Falano** [comment]
It should be fixed now; could you please confirm?

**Comment by derSchotte** [comment]
Now it works like a charm

**Comment by Falano** [comment]
Awesome! Thanks for telling me.

**Comment by gle2n** [comment]
Wow, great response time !
It effectively works perfect now, thanks a lot !
