### ISSUE TITLE
Error to export :/

### ISSUE THREAD

**Issue by diegosarzi** [Falano/kritaSpritesheetManager#8]
I using Debian 10 and krita 4.1.7.101
##################################################

AttributeError
Python 3.7.3: /usr/bin/python3
Sun Apr 5 18:01:22 2020

A problem occurred in a Python script. Here is the sequence of
function calls leading up to the error, in the order they occurred.

/home/gnew/.local/share/krita/pykrita/spritesheetExporter/uispritesheetexporter.py in confirmButton(self=<spritesheetExporter.uispritesheetexporter.UISpritesheetExporter object>)
378 else:
379 # important: we reset spritesheetexporter's spritesExportDir
380 self.exp.spritesExportDir = self.exp.defaultPath
381 self.exp.export()
382 self.mainDialog.hide()
self = <spritesheetExporter.uispritesheetexporter.UISpritesheetExporter object>
self.exp = <spritesheetExporter.spritesheetexporter.SpritesheetExporter object>
self.exp.export = <bound method SpritesheetExporter.export of <spr....spritesheetexporter.SpritesheetExporter object>>

/home/gnew/.local/share/krita/pykrita/spritesheetExporter/spritesheetexporter.py in export(self=<spritesheetExporter.spritesheetexporter.SpritesheetExporter object>, debugging=False)
153 # and if needed input default value
154 if(self.end == self.defaultTime or self.start == self.defaultTime):
155 self.setStartEndFrames()
156 doc.setCurrentTime(self.start)
157 if(debugging):
self = <spritesheetExporter.spritesheetexporter.SpritesheetExporter object>
self.setStartEndFrames = >

/home/gnew/.local/share/krita/pykrita/spritesheetExporter/spritesheetexporter.py in setStartEndFrames(self=<spritesheetExporter.spritesheetexporter.SpritesheetExporter object>)
81 if self.end == self.defaultTime:
82 for layer in layers:
83 self.checkLayerEnd(layer, doc)
84 # get first frame of all visible layers
85 if self.start == self.defaultTime:
self = <spritesheetExporter.spritesheetexporter.SpritesheetExporter object>
self.checkLayerEnd = <bound method SpritesheetExporter.checkLayerEnd ....spritesheetexporter.SpritesheetExporter object>>
layer = <PyKrita.krita.Node object>
doc = <PyKrita.krita.Document object>

/home/gnew/.local/share/krita/pykrita/spritesheetExporter/spritesheetexporter.py in checkLayerEnd(self=<spritesheetExporter.spritesheetexporter.SpritesheetExporter object>, layer=<PyKrita.krita.Node object>, doc=<PyKrita.krita.Document object>)
46 if layer.visible():
47 if layer.animated():
48 frame = doc.fullClipRangeEndTime()
49 while not (layer.hasKeyframeAtTime(frame)
50 or frame < 0):
frame undefined
doc = <PyKrita.krita.Document object>
doc.fullClipRangeEndTime undefined
AttributeError: 'Document' object has no attribute 'fullClipRangeEndTime'
cause = None
class = <class 'AttributeError'>
context = None
delattr = <method-wrapper 'delattr' of AttributeError object>
dict = {}
dir =
doc = 'Attribute not found.'
eq = <method-wrapper 'eq' of AttributeError object>
format =
ge = <method-wrapper 'ge' of AttributeError object>
getattribute = <method-wrapper 'getattribute' of AttributeError object>
gt = <method-wrapper 'gt' of AttributeError object>
hash = <method-wrapper 'hash' of AttributeError object>
init = <method-wrapper 'init' of AttributeError object>
init_subclass =
le = <method-wrapper 'le' of AttributeError object>
lt = <method-wrapper 'lt' of AttributeError object>
ne = <method-wrapper 'ne' of AttributeError object>
new =
reduce =
reduce_ex =
repr = <method-wrapper 'repr' of AttributeError object>
setattr = <method-wrapper 'setattr' of AttributeError object>
setstate =
sizeof =
str = <method-wrapper 'str' of AttributeError object>
subclasshook =
suppress_context = False
traceback =
args = ("'Document' object has no attribute 'fullClipRangeEndTime'",)
with_traceback =

The above is a description of an error in a Python program. Here is
the original traceback:

Traceback (most recent call last):
File "/home/gnew/.local/share/krita/pykrita/spritesheetExporter/uispritesheetexporter.py", line 381, in confirmButton
self.exp.export()
File "/home/gnew/.local/share/krita/pykrita/spritesheetExporter/spritesheetexporter.py", line 155, in export
self.setStartEndFrames()
File "/home/gnew/.local/share/krita/pykrita/spritesheetExporter/spritesheetexporter.py", line 83, in setStartEndFrames
self.checkLayerEnd(layer, doc)
File "/home/gnew/.local/share/krita/pykrita/spritesheetExporter/spritesheetexporter.py", line 48, in checkLayerEnd
frame = doc.fullClipRangeEndTime()
AttributeError: 'Document' object has no attribute 'fullClipRangeEndTime'

**Comment by Falano** [comment]
Hi!
Thanks for having opened a new issue.
The script doesn't work with older krita versions, you need at least 4.2.0. If for some reason you can't upgrade your Krita, you may be able to make it work by checking "Custom Export Settings" and changing the Start and End values to the ones you'll use. It's kinda tedious after a while, though, and the newer krita versions have cool features, so in your place I'd upgrade it instead.

**Comment by Falano** [comment]
I'm closing the issue since I'm assuming it worked. If it didn't, don't hesitate to comment here and I'll reopen it, and if you have other unrelated issues, open a new one.
Have a nice day
